name: fysstk
channels: 
  - conda
dependencies:
  - python=
  - notebook
  - ipykernel
  - autograd
  - scikit-learn
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - xarray
    - keras
    - tensorflow
    - torch